# Site settings
title: NoteBook
email: ""
description: "It's the niceties that make the difference fate gives us the hand, and we play the cards."
url: "https://nlgithubwp.github.io"
baseurl: "/tech-notebook"
facebook_username: ""
twitter_username: ""
instagram_username: ""
github_username: ""
deviantart_username: ""
flickr_username: ""
discus_shortname: ""
share: true

# Owner/author information

# Settings for comments helper
comments:
  provider: disqus
  disqus:
    short_name: ""

# Internal nav
nav:
  - GALLERY: "https://nlgithubwp.github.io/tech-notebook/gallery/"
  - JOURNAL: "https://nlgithubwp.github.io/tech-notebook/journal/"
  - ABOUT: "https://nlgithubwp.github.io/tech-notebook/about/"
  - CV: "https://nlgithubwp.github.io/tech-notebook/resume/"

# All translation keys
translations:
  permalink: "/404.html"

# Server
destination: "./_site"
port: 4000

# Build settings
markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM
  syntax_highlighter: pygments
permalink: "/journal/:title/"
paginate: 5
paginate_path: "/journal/page:num/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

exclude:
  - "less"
  - "node_modules"
  - "Gruntfile.js"
  - "package.json"
  - "README.md"

# SiteMap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/writing/"
  change_frequency_name: "change_frequency"
  priority_name: "priority"
