#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#- jekyll-remote-theme
theme: jekyll-theme-hacker

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      class: wide               # new
      show_date: true           # new
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true